---
abstract: 'interpret string as Perl source'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Test::More: 0
  perl: 5.008004
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.008004
  strict: 0
  warnings: 0
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-Perl
provides:
  Parse::Perl:
    file: lib/Parse/Perl.pm
    version: 0.004
  Parse::Perl::CopHintsHash:
    file: lib/Parse/Perl.pm
    version: 0.004
  Parse::Perl::Environment:
    file: lib/Parse/Perl.pm
    version: 0.004
requires:
  Exporter: 0
  XSLoader: 0
  parent: 0
  perl: 5.008004
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
